### PR TITLE
Bump docker-gen, forego, python versions

### PR DESCRIPTION
**Pull request by techiebod**
Bumping docker-gen version to get rid of the irritating "invalid value" log spam :)

See: https://github.com/nginx-proxy/docker-gen/pull/494

### CODE REVIEW

**Comment by techiebod** [comment]
Bumped forego and python whilst I'm here, and saved us a few mb by switching to the slim image too

**Comment by hardillb** [comment]
Having just watched this build I think the python version might end up getting reset by the install of `build-essential` but we can leave it as is.

Thanks.

**Comment by hardillb** [comment]
New version pushed to docker hub

**Comment by techiebod** [comment]
Your comment made me go look a bit harder, and it looks like we don't need the whole set of packages installed at all, nor do we need to install the mdns-publisher pip, or at least at first glance it builds and runs fine without these, want an updated PR?

**Comment by hardillb** [comment]
I'd you've got the time to play, go for it

**Pull request merged**
